version: '3.8'
services:
  db:
    image: postgres:15
    container_name: brickbyte-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysuperpass123
      POSTGRES_DB: brickbytedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@brickbyte.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  pgdata:
